server:
  port: 9090

spring:
  application:
    name: hystrix-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:10086/eureka/

service-url:
  user-service: http://user-service