server:
  port: 10000
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica2
  client:
    # 指定是否从注册中心获取服务（注册中心不需要开启）
    fetch-registry: true
    # 指定是否将服务注册到注册中心（注册中心不需要开启）
    register-with-eureka: true
    service-url:
      # 注册到另一个Eureka注册中心
      defaultZone: http://replica1:10010/eureka
