server:
  port: 10090

spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost
  client:
    # 获取注册实例列表
    fetch-registry: true
    # 注册到Eureka注册中心
    register-with-eureka: true
    service-url:
    # defaultZone: http://localhost:10086/eureka
      defaultZone: http://replica1:10010/eureka/, http://replica2:10000/eureka/
