server:
  port: 10090

spring:
  application:
    name: eureka-security-client

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 此处需要修改注册中心地址格式
      defaultZone: http://root:root@localhost:10086/eureka/

